
(()=>{const {ethers}=window,CFG=window.APP_CONFIG,ABIS=window.ABIS;
const LS={meta:"votage_meta",likes:"votage_likes",verified:"votage_verified",points:"votage_points",streak:"votage_streak",profile:"votage_profile"};
let S={provider:null,signer:null,address:null,bm:null,win:null,usdc:null,rd:null,battles:[],cat:"All",q:"",duration:1,imgA:null,imgB:null,voteCtx:null};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], fmtAddr=a=>a?a.slice(0,6)+"..."+a.slice(-4):"—", now=()=>Math.floor(Date.now()/1000), get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}, set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const fmtUSD=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(n||0), fmtNum=n=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(n||0);
function nav(){const p=document.body.dataset.page;$$("[data-nav]").forEach(x=>{if(x.dataset.nav===p|| (p==="home"&&x.dataset.nav==="home"))x.classList.add("active")})}
async function wallet(){if(!window.ethereum){alert("MetaMask is required.");return false}if(!S.provider)S.provider=new ethers.BrowserProvider(window.ethereum);const acc=await S.provider.send("eth_requestAccounts",[]);S.signer=await S.provider.getSigner();S.address=acc[0];S.bm=new ethers.Contract(CFG.contracts.battleManager,ABIS.battle,S.signer);S.win=new ethers.Contract(CFG.contracts.win,ABIS.erc20,S.signer);S.usdc=new ethers.Contract(CFG.contracts.usdc,ABIS.erc20,S.signer);S.rd=new ethers.Contract(CFG.contracts.rewardDistributor,ABIS.rd,S.signer);uiWallet();await loadBattles();render("feed",false);render("resultsFeed",true);market();points();return true}
function uiWallet(){const b=$("#connectBtn"),c=$("#helloChip");if(S.address){b.innerHTML='<img class="icon" src="assets/icons/wallet.svg" alt="" />'+fmtAddr(S.address);c.textContent='Hello, '+fmtAddr(S.address)}}
async function loadBattles(){if(!S.bm)return[];const count=Number(await S.bm.battleCount());const meta=get(LS.meta,{}), likes=get(LS.likes,{});const arr=[];for(let i=1;i<=count;i++){try{const raw=await S.bm.battles(i);arr.push({id:i,creator:raw.creator,startTime:Number(raw.startTime),endTime:Number(raw.endTime),totalA:Number(raw.totalA),totalB:Number(raw.totalB),resolved:raw.resolved,winner:Number(raw.winner),title:(meta[i]||{}).title||`Battle #${i}`,description:(meta[i]||{}).description||"On-chain battle created without full metadata in the deployed contract.",category:(meta[i]||{}).category||"General",labelA:(meta[i]||{}).labelA||"Option A",labelB:(meta[i]||{}).labelB||"Option B",imgA:(meta[i]||{}).imgA||"assets/images/hero.webp",imgB:(meta[i]||{}).imgB||"assets/images/home-inline-banner.webp",likes:likes[i]||0,comments:0})}catch(e){}}S.battles=arr;sidebar();return arr}
function score(b){const value=(b.totalA+b.totalB)/1e6, age=Math.max(.1,(now()-b.startTime)/3600), rem=Math.max(.1,(b.endTime-now())/3600), valueScore=Math.log(value+1)*5, rec=(1/(age+1))*30, time=(!b.resolved?(1/(rem+1))*20:0);return valueScore+rec+time}
function remain(end){const d=Math.max(0,end-now()),h=Math.floor(d/3600),m=Math.floor((d%3600)/60);return `${String(h).padStart(2,"0")}h ${String(m).padStart(2,"0")}m remaining`}
function progress(start,end){const t=Math.max(1,end-start),e=Math.min(t,Math.max(0,now()-start));return e/t*100}
function filtered(ended){let out=[...S.battles];out=ended?out.filter(b=>b.resolved||now()>=b.endTime):out.filter(b=>!b.resolved&&now()<b.endTime);if(S.cat!=="All")out=out.filter(b=>b.category===S.cat);if(S.q){const q=S.q.toLowerCase();out=out.filter(b=>[b.title,b.description,b.labelA,b.labelB].join(" ").toLowerCase().includes(q))}return out.sort((a,b)=>score(b)-score(a))}
function card(b){const total=b.totalA+b.totalB,pA=total?Math.round(b.totalA/total*100):50,pB=100-pA,ended=b.resolved||now()>=b.endTime,wA=ended&&b.winner===1,wB=ended&&b.winner===2,fill=ended?"#9ca3af":(pA>=pB?"var(--blue)":"var(--red)");
return `<article class="battle-card card ${ended?'ended-card':''}"><div class="battle-head"><div class="userline"><img src="assets/images/avatar.webp" alt=""><div class="user-meta"><strong>Hello, ${fmtAddr(b.creator)}</strong><small>${b.category}</small></div></div><div class="head-right"><span class="badge ${ended?'ended':'live'}">${ended?'Ended':'Live'}</span><span class="money-added">${ended?'Final snapshot':fmtUSD(Math.max(0,(total/1e6)*0.04))+' added in last hour'}</span></div></div><div class="battle-copy"><h2>${esc(b.title)}</h2><p>${esc(b.description)}</p></div><div class="battle-grid"><div class="panel"><div class="panel-name">${esc(b.labelA)}</div><div class="media-wrap"><img src="${b.imgA}" alt=""></div><button class="vote-btn ${ended?(wA?'vote-a winner-a':'vote-a'):'vote-a'}" data-vote="${b.id}" data-side="1"><span class="label">${esc(b.labelA)}</span><span class="pct">${pA}%</span></button></div><div class="panel"><div class="panel-name">${esc(b.labelB)}</div><div class="media-wrap"><img src="${b.imgB}" alt=""></div><button class="vote-btn ${ended?(wB?'vote-b winner-b':'vote-b'):'vote-b'}" data-vote="${b.id}" data-side="2"><span class="pct">${pB}%</span><span class="label">${esc(b.labelB)}</span></button></div></div><div class="meta-top"><div class="time-wrap"><img class="icon" src="assets/icons/clock.svg" alt=""><div class="time-bar"><div class="time-fill ${ended?'ended':''}" style="width:${progress(b.startTime,b.endTime)}%;background:${fill}"></div></div><span>${ended?'Ended':remain(b.endTime)}</span></div></div><div class="post-actions"><div class="actions-left"><button class="icon-text" data-like="${b.id}"><img src="assets/icons/heart.svg" alt="">${b.likes}</button><button class="icon-text"><img src="assets/icons/comment.svg" alt="">0</button><button class="icon-text" data-sharex="${b.id}"><img src="assets/icons/share.svg" alt="">Share on X</button><button class="icon-text" data-copy="${b.id}"><img src="assets/icons/copy.svg" alt="">Copy link</button></div><div class="actions-right"><span>${fmtUSD(total/1e6)} at stake</span><span>${Math.round(total/1e6)} voters</span></div></div></article>`}
function render(id,ended){const el=document.getElementById(id);if(!el)return;const list=filtered(ended);el.innerHTML=list.length?list.map(card).join(""):'<section class="card empty-state">No battles found.</section>';bindCards()}
function bindCards(){$$("[data-like]").forEach(b=>b.onclick=()=>{const likes=get(LS.likes,{}),id=b.dataset.like;likes[id]=(likes[id]||0)+1;set(LS.likes,likes);const battle=S.battles.find(x=>String(x.id)===id);if(battle)battle.likes=likes[id];render(document.body.dataset.page==="results"?"resultsFeed":"feed",document.body.dataset.page==="results")});$$("[data-copy]").forEach(b=>b.onclick=async()=>{const url=`${location.origin}${location.pathname}?battle=${b.dataset.copy}`;try{await navigator.clipboard.writeText(url);alert("Link copied.")}catch(e){}});$$("[data-sharex]").forEach(b=>b.onclick=()=>{const battle=S.battles.find(x=>String(x.id)===b.dataset.sharex);const text=encodeURIComponent(`Choose your side on Votage: ${battle?.title||"Battle"}`);window.open(`https://twitter.com/intent/tweet?text=${text}&url=${encodeURIComponent(location.origin+"/?ref="+(S.address||""))}`,"_blank")});$$("[data-vote]").forEach(b=>b.onclick=()=>{S.voteCtx={id:Number(b.dataset.vote),side:Number(b.dataset.side)};$("#voteModalBody").innerHTML='<div class="field"><label>Battle ID</label><input value="'+S.voteCtx.id+'" disabled></div><div class="field"><label>Side</label><input value="'+(S.voteCtx.side===1?"Option A":"Option B")+'" disabled></div><div class="field"><label>USDC amount</label><select id="voteAmountSelect"><option value="1">1 USDC</option><option value="5">5 USDC</option><option value="10">10 USDC</option></select></div>';open("voteModal")})}
function sidebar(){const lb=$("#leaderboard");if(lb){const leaders={};S.battles.forEach(b=>leaders[b.creator]=(leaders[b.creator]||0)+(b.totalA+b.totalB)/1e6);lb.innerHTML=Object.entries(leaders).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([a,v],i)=>`<div class="list-item"><span>#${i+1} ${fmtAddr(a)}</span><strong>${fmtUSD(v)}</strong></div>`).join("")||'<div class="small">Connect wallet and vote to populate the on-chain leaderboard.</div>'}$("#battleCountMetric")&&($("#battleCountMetric").textContent=String(S.battles.length));$("#winAddressShort")&&($("#winAddressShort").textContent=fmtAddr(CFG.contracts.win));$("#bmAddressShort")&&($("#bmAddressShort").textContent=fmtAddr(CFG.contracts.battleManager));if($("#airdropMetric")&&S.bm)S.bm.airdropPool().then(v=>$("#airdropMetric").textContent=fmtUSD(Number(v)/1e6)).catch(()=>{})}
function open(id){document.getElementById(id)?.classList.add("open")}function close(id){document.getElementById(id)?.classList.remove("open")}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function bindModalClose(){$$("[data-close-modal]").forEach(b=>b.onclick=()=>close(b.dataset.closeModal));["createModal","voteModal"].forEach(id=>document.getElementById(id)?.addEventListener("click",e=>{if(e.target.id===id)close(id)}))}
function initCreate(){const wrap=$("#durationChips");if(wrap){wrap.innerHTML="";for(let i=1;i<=7;i++){const b=document.createElement("button");b.className="duration-chip"+(i===1?" active":"");b.textContent=`${i} ${i===1?"Day":"Days"}`;b.onclick=()=>{S.duration=i;$$(".duration-chip").forEach(x=>x.classList.remove("active"));b.classList.add("active")};wrap.appendChild(b)}}["battleTitle","battleDescription","labelA","labelB","battleCategory"].forEach(id=>$("#"+id)?.addEventListener("input",preview));bindDrop("A");bindDrop("B");preview()}
function bindDrop(which){const dz=$("#drop"+which),fi=$("#file"+which);if(!dz||!fi)return;dz.onclick=()=>fi.click();["dragenter","dragover"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.style.background="#f8fafc"}));["dragleave","drop"].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.style.background="#fff"}));dz.addEventListener("drop",e=>{const f=e.dataTransfer.files[0];if(f)processImg(which,f)});fi.onchange=e=>{const f=e.target.files[0];if(f)processImg(which,f)}}
async function processImg(which,file){const allowed=["image/jpeg","image/png","image/webp"];if(!allowed.includes(file.type)){ $("#imageError").textContent="Only JPG, PNG or WEBP are supported."; return}if(file.size>2*1024*1024){$("#imageError").textContent="This file is too large. Please upload an image under 2MB."; return}$("#imageError").textContent="";const data=await fileToDataUrl(file),webp=await cropWebp(data,800,500,.75);S["img"+which]=webp;const dz=$("#drop"+which);dz.classList.add("has-image");dz.innerHTML=`<img src="${webp}" alt="">`;preview()}
function fileToDataUrl(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(file)})}
function cropWebp(src,w,h,q){return new Promise(res=>{const img=new Image();img.onload=()=>{const c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d"),sc=Math.max(w/img.width,h/img.height),dw=img.width*sc,dh=img.height*sc,dx=(w-dw)/2,dy=(h-dh)/2;x.drawImage(img,dx,dy,dw,dh);res(c.toDataURL("image/webp",q))};img.src=src})}
function preview(){const root=$("#battlePreview");if(!root)return;const t=$("#battleTitle")?.value||"Battle preview",d=$("#battleDescription")?.value||"This preview updates as you type.",a=$("#labelA")?.value||"Option A",b=$("#labelB")?.value||"Option B";root.innerHTML=`<div class="small" style="margin-bottom:10px">Preview</div><div style="font-weight:800;font-size:22px;margin-bottom:8px">${esc(t)}</div><div class="small" style="margin-bottom:12px">${esc(d)}</div><div class="battle-grid"><div class="panel"><div class="panel-name">${esc(a)}</div><div class="media-wrap"><img src="${S.imgA||'assets/images/hero.webp'}" alt=""></div><button class="vote-btn vote-a"><span class="label">${esc(a)}</span><span class="pct">59%</span></button></div><div class="panel"><div class="panel-name">${esc(b)}</div><div class="media-wrap"><img src="${S.imgB||'assets/images/home-inline-banner.webp'}" alt=""></div><button class="vote-btn vote-b"><span class="pct">41%</span><span class="label">${esc(b)}</span></button></div></div>`}
async function createBattle(){if(!await wallet())return;const title=$("#battleTitle").value.trim(),description=$("#battleDescription").value.trim(),category=$("#battleCategory").value,labelA=$("#labelA").value.trim(),labelB=$("#labelB").value.trim();if(!title||!labelA||!labelB||!S.imgA||!S.imgB){alert("Title, both option labels and both images are required.");return}try{const tx=await S.bm.createBattle(S.duration);await tx.wait();const id=Number(await S.bm.battleCount()),meta=get(LS.meta,{});meta[id]={title,description,category,labelA,labelB,imgA:S.imgA,imgB:S.imgB};set(LS.meta,meta);close("createModal");await loadBattles();render("feed",false);render("resultsFeed",true);alert("Battle created on-chain.")}catch(e){console.error(e);alert("Create battle failed.")}}
async function voteConfirm(){if(!await wallet())return;const usd=Number($("#voteAmountSelect").value||"1"),amount=BigInt(Math.round(usd*1_000_000));try{const allowance=await S.usdc.allowance(S.address,CFG.contracts.battleManager);if(allowance<amount){const txa=await S.usdc.approve(CFG.contracts.battleManager,amount);await txa.wait()}const tx=await S.bm.vote(S.voteCtx.id,S.voteCtx.side,amount);await tx.wait();if(get(LS.verified,false)){const pts=Number(localStorage.getItem(LS.points)||"0")+1;localStorage.setItem(LS.points,String(pts));$("#localPoints")&&($("#localPoints").textContent=String(pts))}close("voteModal");await loadBattles();render(document.body.dataset.page==="results"?"resultsFeed":"feed",document.body.dataset.page==="results");alert("Vote submitted.")}catch(e){console.error(e);alert("Vote failed. Check USDC balance and approval.")}}
async function market(){if(!S.address||!$("#marketTotalSupply"))return;try{const supply=await S.win.totalSupply(),bal=await S.win.balanceOf(S.address),cb=await S.bm.contractBalances();$("#marketTotalSupply").textContent=fmtNum(Number(ethers.formatUnits(supply,18)));$("#marketWalletWin").textContent=fmtNum(Number(ethers.formatUnits(bal,18)));$("#marketContractUsdc").textContent=fmtUSD(Number(ethers.formatUnits(cb[0],6)));$("#marketContractWin").textContent=fmtNum(Number(ethers.formatUnits(cb[1],18)))}catch(e){}}
async function points(){if(!$("#claimableWin"))return;$("#verifyStatusChip").textContent=get(LS.verified,false)?"Unlocked":"Locked";$("#localPoints").textContent=localStorage.getItem(LS.points)||"0";$("#localStreak").textContent=(localStorage.getItem(LS.streak)||"0")+" days";const p=get(LS.profile,{});$("#profileUsername")&&($("#profileUsername").value=p.username||"");$("#profileX")&&($("#profileX").value=p.x||"");$("#refLink")&&($("#refLink").value=S.address?`${location.origin}${location.pathname}?ref=${S.address}`:location.href);if(S.address&&S.rd){try{const r=await S.rd.rewards(S.address),c=await S.rd.claimed(S.address);$("#claimableWin").textContent=fmtNum(Number(ethers.formatUnits(r,18)))+" WIN";$("#claimedStatus").textContent=c?"Yes":"No"}catch(e){}}}
function pointsBinds(){$("#verifyPointsBtn")?.addEventListener("click",()=>{set(LS.verified,true);$("#verifyStatusChip").textContent="Unlocked";const pts=Number(localStorage.getItem(LS.points)||"0")+50;localStorage.setItem(LS.points,String(pts));$("#localPoints")&&($("#localPoints").textContent=String(pts));alert("Verification simulated for this build.")});$("#claimRewardBtn")?.addEventListener("click",async()=>{if(!await wallet())return;try{const tx=await S.rd.claim();await tx.wait();points();alert("Reward claim submitted.")}catch(e){alert("Claim failed or no rewards available.")}});$("#connectXBtn")?.addEventListener("click",()=>{const pts=Number(localStorage.getItem(LS.points)||"0")+250;localStorage.setItem(LS.points,String(pts));$("#localPoints")&&($("#localPoints").textContent=String(pts));alert("X connection simulated in this build.")});$("#profileUsername")?.addEventListener("input",()=>saveProfile());$("#profileX")?.addEventListener("input",()=>saveProfile());$("#shareReferralBtn")?.addEventListener("click",()=>{const ref=S.address?`${location.origin}/?ref=${S.address}`:location.href;window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent("Join me on Votage and choose your side.")}&url=${encodeURIComponent(ref)}`,"_blank")})}
function saveProfile(){set(LS.profile,{username:$("#profileUsername")?.value||"",x:$("#profileX")?.value||""})}
async function init(){nav();bindModalClose();$("#connectBtn")?.addEventListener("click",wallet);$("#openCreateBtn")?.addEventListener("click",()=>open("createModal"));$("#heroCreateBtn")?.addEventListener("click",()=>open("createModal"));$("#submitBattleBtn")?.addEventListener("click",createBattle);$("#confirmVoteBtn")?.addEventListener("click",voteConfirm);$("#refreshFeedBtn")?.addEventListener("click",async()=>{if(await wallet()){}});
$$(".chip").forEach(b=>b.addEventListener("click",()=>{$$(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");S.cat=b.dataset.cat;render("feed",false)}));$("#searchInput")?.addEventListener("input",e=>{S.q=e.target.value.trim();render("feed",false)});
initCreate();pointsBinds();
if(window.ethereum){try{await wallet()}catch(e){}}
}
window.addEventListener("load",init);
})();
